version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
     - .:/var/www/html
    ports:
     - "${APP_PORT}:80"
    networks:
     - wwnet
  mysql:
    image: mysql:5.7
    ports:
     - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - wwnet
  node:
    image: node:10.15.3
    volumes:
     - .:/usr/src
    networks:
     - wwnet

  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - wwnet
networks:
  wwnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"